# Generated by Django 2.1.3 on 2018-12-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
