# Generated by Django 2.1.3 on 2018-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_auto_20181217_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
