# Generated by Django 2.1.3 on 2018-12-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_auto_20181218_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='user',
        ),
    ]
