# Generated by Django 2.1.3 on 2018-12-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20181217_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateTimeField(),
        ),
    ]
