# Generated by Django 2.1.3 on 2018-12-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_auto_20181230_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='name',
        ),
    ]
