# Generated by Django 2.1.3 on 2018-12-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_remove_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/image/im_%Y_%m_%d'),
        ),
    ]
