# Generated by Django 2.2.3 on 2019-07-22 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0002_auto_20181231_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 13, 21, 26, 509243, tzinfo=utc)),
        ),
    ]
