# Generated by Django 2.1.1 on 2019-07-22 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0004_auto_20190722_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 13, 45, 43, 516579, tzinfo=utc)),
        ),
    ]
